# fly.toml file generated for odrv on 2021-03-20T00:03:06+08:00

app = "odrv"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "onedirect"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    port = "8080"
    restart_limit = 6
    timeout = "2s"
